In [9]:
# Dependencies and Setup
import pandas as pd
import numpy as np

# File to Load (Remember to Change These)
file_to_load = "TripData_2018.csv"

# Read Purchasing File and store into Pandas data frame
Trip_Data = pd.read_csv(file_to_load)
Trip_Data.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,Age,gender
0,254,11/1/2018 12:00:13 AM,11/1/2018 12:04:27 AM,3522.0,37 St & 24 Ave,40.770148,-73.912094,3513.0,21 St & Hoyt Ave S,40.774645,-73.923706,34117,Subscriber,1992,27,1
1,833,11/1/2018 12:00:16 AM,11/1/2018 12:14:09 AM,252.0,MacDougal St & Washington Sq,40.732264,-73.998522,251.0,Mott St & Prince St,40.723180,-73.994800,32569,Subscriber,1986,33,2
2,683,11/1/2018 12:00:18 AM,11/1/2018 12:11:41 AM,3405.0,5 St & 6 Ave,40.670484,-73.982090,3584.0,Eastern Pkwy & Franklin Ave,40.670777,-73.957680,15795,Subscriber,1985,34,1
3,1840,11/1/2018 12:00:19 AM,11/1/2018 12:30:59 AM,3150.0,E 85 St & York Ave,40.775369,-73.948034,297.0,E 15 St & 3 Ave,40.734232,-73.986923,33290,Subscriber,1994,25,1
4,1212,11/1/2018 12:00:47 AM,11/1/2018 12:21:00 AM,325.0,E 19 St & 3 Ave,40.736245,-73.984738,212.0,W 16 St & The High Line,40.743349,-74.006818,17411,Subscriber,1989,30,1

In [17]:
Clean_Trip_Data = Trip_Data.dropna()
Clean_Trip_Data.head(15)

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,Age,gender
0,254,11/1/2018 12:00:13 AM,11/1/2018 12:04:27 AM,3522.0,37 St & 24 Ave,40.770148,-73.912094,3513.0,21 St & Hoyt Ave S,40.774645,-73.923706,34117,Subscriber,1992,27,1
1,833,11/1/2018 12:00:16 AM,11/1/2018 12:14:09 AM,252.0,MacDougal St & Washington Sq,40.732264,-73.998522,251.0,Mott St & Prince St,40.723180,-73.994800,32569,Subscriber,1986,33,2
2,683,11/1/2018 12:00:18 AM,11/1/2018 12:11:41 AM,3405.0,5 St & 6 Ave,40.670484,-73.982090,3584.0,Eastern Pkwy & Franklin Ave,40.670777,-73.957680,15795,Subscriber,1985,34,1
3,1840,11/1/2018 12:00:19 AM,11/1/2018 12:30:59 AM,3150.0,E 85 St & York Ave,40.775369,-73.948034,297.0,E 15 St & 3 Ave,40.734232,-73.986923,33290,Subscriber,1994,25,1
4,1212,11/1/2018 12:00:47 AM,11/1/2018 12:21:00 AM,325.0,E 19 St & 3 Ave,40.736245,-73.984738,212.0,W 16 St & The High Line,40.743349,-74.006818,17411,Subscriber,1989,30,1
5,792,11/1/2018 12:01:08 AM,11/1/2018 12:14:20 AM,303.0,Mercer St & Spring St,40.723627,-73.999496,3260.0,Mercer St & Bleecker St,40.727064,-73.996621,15344,Customer,1995,24,2
6,243,11/1/2018 12:01:12 AM,11/1/2018 12:05:15 AM,3571.0,Bedford Ave & Bergen St,40.676368,-73.952918,3562.0,Classon Ave & St Marks Ave,40.676520,-73.959608,34053,Subscriber,1980,39,2
7,460,11/1/2018 12:01:12 AM,11/1/2018 12:08:53 AM,3458.0,W 55 St & 6 Ave,40.763094,-73.978350,477.0,W 41 St & 8 Ave,40.756405,-73.990026,14992,Subscriber,1970,49,1
8,778,11/1/2018 12:01:15 AM,11/1/2018 12:14:13 AM,3579.0,Sterling Pl & Bedford Ave,40.672695,-73.954131,3571.0,Bedford Ave & Bergen St,40.676368,-73.952918,35229,Subscriber,1980,39,2
9,178,11/1/2018 12:01:32 AM,11/1/2018 12:04:30 AM,3467.0,W Broadway & Spring Street,40.724947,-74.001659,151.0,Cleveland Pl & Spring St,40.722104,-73.997249,31476,Subscriber,1978,41,1
10,547,11/1/2018 12:01:22 AM,11/1/2018 12:10:29 AM,3502.0,Lexington Ave & E 111 St,40.795412,-73.944123,3553.0,Frederick Douglass Blvd & W 112 St,40.801694,-73.957145,26878,Subscriber,1987,32,1
11,761,11/1/2018 12:01:26 AM,11/1/2018 12:14:08 AM,379.0,W 31 St & 7 Ave,40.749156,-73.991600,268.0,Howard St & Centre St,40.719105,-73.999733,34202,Subscriber,1984,35,1
12,191,11/1/2018 12:01:32 AM,11/1/2018 12:04:44 AM,382.0,University Pl & E 14 St,40.734927,-73.992005,223.0,W 13 St & 7 Ave,40.737815,-73.999947,19670,Subscriber,1975,44,1
13,315,11/1/2018 12:01:34 AM,11/1/2018 12:06:50 AM,3591.0,21 St & 31 Dr,40.765900,-73.930819,3593.0,31 St & Broadway,40.761584,-73.925921,29743,Subscriber,1983,36,1
14,1546,11/1/2018 12:01:50 AM,11/1/2018 12:27:36 AM,491.0,E 24 St & Park Ave S,40.740964,-73.986022,460.0,S 4 St & Wythe Ave,40.712859,-73.965903,32957,Subscriber,1988,31,1

In [20]:
Clean_Trip_Data.to_csv('Clean_Trip_Data.csv',index=True,header=True)